CC=g++

CFLAGS=-c -Wall

VEKTORIAI_SOURCES=vektoriai.cpp mokinys.cpp funkcijos.h
LIST_SOURCES=list.cpp mokinys1.cpp funkcijos1.h
DEQUE_SOURCES=deque.cpp mokinys2.cpp funkcijos2.h

VEKTORIAI_OBJECTS=$(VEKTORIAI_SOURCES:.cpp=.o)
LIST_OBJECTS=$(LIST_SOURCES:.cpp=.o)
DEQUE_OBJECTS=$(DEQUE_SOURCES:.cpp=.o)

VEKTORIAI_EXECUTABLE=vektoriai
LIST_EXECUTABLE=list
DEQUE_EXECUTABLE=deque

all: $(VEKTORIAI_EXECUTABLE) $(LIST_EXECUTABLE) $(DEQUE_EXECUTABLE)

$(VEKTORIAI_EXECUTABLE): $(VEKTORIAI_OBJECTS)
	$(CC) $(VEKTORIAI_OBJECTS) -o $@

$(LIST_EXECUTABLE): $(LIST_OBJECTS)
	$(CC) $(LIST_OBJECTS) -o $@

$(DEQUE_EXECUTABLE): $(DEQUE_OBJECTS)
	$(CC) $(DEQUE_OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	del *.o *.exe
